Repository CiscoDevNet/terraform-provider-aci, pull requests merged in 2020-01, with the labels that each got.

#16 Added logic to handle panics
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/client.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#17 Added new cipher suites and TLS version support for capic:
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/client.go
  vendor/modules.txt
Labels: dependencies, size/XS

#18 Changed the new rn format for cloudextepg selector
  aci/resource_aci_cloudextepselector.go
Labels: size/XS

#19 Changelog update
  CHANGELOG.md
Labels: size/XS
