Repository CiscoDevNet/terraform-provider-aci, pull requests merged in 2020-09, with the labels that each got.

#105 Cacit 63 check subnet resources
  aci/provider.go
  website/aci.erb
  website/docs/d/infraaccbndlgrp.html.markdown
  website/docs/r/infraaccbndlgrp.html.markdown
Labels: documentation, size/XL

#115 CACIT-65 updated bd and subnet
  aci/resource_aci_fvbd.go
  aci/resource_aci_fvsubnet.go
Labels: size/M

#116 CACIT-66 issues fixed
  aci/resource_aci_fvaepg.go
  aci/resource_aci_infranodeblk.go
  website/docs/r/fvaepg.html.markdown
Labels: documentation, size/M

#114 Rename aci_switch_association to aci_leaf_selector
  aci/provider.go
  aci/resource_aci_infraleafs_test.go
  aci/resource_aci_infranodeblk_test.go
  website/aci.erb
  website/docs/d/infraleafs.html.markdown
  website/docs/d/infranodeblk.html.markdown
  website/docs/r/infraleafs.html.markdown
  website/docs/r/infranodeblk.html.markdown
Labels: documentation, size/M

#120 Updated changelog for release
  CHANGELOG.md
Labels: size/XS

#122 Cacit 68 69
  aci/data_source_aci_fabricpathep.go
  aci/provider.go
  aci/resource_aci_vzbrcp.go
  aci/resource_aci_vzentry.go
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/auth.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/client.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/fabricPathEp_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/firmwareCtrlrRunning_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/fabric_path_ep.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/firmware_ctrlr_running.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/maint_maint_p.go
  vendor/modules.txt
  website/aci.erb
  website/docs/d/fabricpathep.html.markdown
Labels: dependencies, documentation, size/XL

#123 CACIT-71 inline block added
  aci/resource_aci_infranodep.go
  website/docs/r/infranodep.html.markdown
Labels: documentation, size/XL
