Repository CiscoDevNet/terraform-provider-aci, pull requests merged in 2020-06, with the labels that each got.

#45 Cacit 31 port text2num conversion
  aci/resource_aci_vzentry.go
Labels: size/S

#46 CACIT-33: Updated the logic for parentDN
  aci/resource_aci_aaausercert.go
  aci/resource_aci_cloudapp.go
  aci/resource_aci_cloudawsprovider.go
  aci/resource_aci_cloudcidr.go
  aci/resource_aci_cloudctxprofile.go
  aci/resource_aci_cloudepg.go
  aci/resource_aci_cloudepselector.go
  aci/resource_aci_cloudextepg.go
  aci/resource_aci_cloudextepselector.go
  aci/resource_aci_cloudregion.go
  aci/resource_aci_cloudsubnet.go
  aci/resource_aci_cloudzone.go
  aci/resource_aci_fabricnodeblk_FirmWare.go
  aci/resource_aci_fabricnodeblk_MaintGrp.go
  aci/resource_aci_fvaepg.go
  aci/resource_aci_fvap.go
  aci/resource_aci_fvbd.go
  aci/resource_aci_fvctx.go
  aci/resource_aci_fvepretpol.go
  aci/resource_aci_fvnsencapblk.go
  aci/resource_aci_fvrspathatt.go
  aci/resource_aci_fvsubnet.go
  aci/resource_aci_infrahports.go
  aci/resource_aci_infraleafs.go
  aci/resource_aci_infraportblk.go
  aci/resource_aci_infraprovacc.go
  aci/resource_aci_infrasubportblk.go
  aci/resource_aci_l3extinstp.go
  aci/resource_aci_l3extlifp.go
  aci/resource_aci_l3extlnodep.go
  aci/resource_aci_l3extout.go
  aci/resource_aci_l3extrsnodel3outatt.go
  aci/resource_aci_l3extsubnet.go
  aci/resource_aci_monepgpol.go
  aci/resource_aci_ospfifpol.go
  aci/resource_aci_rtctrlattrp.go
  aci/resource_aci_spandestgrp.go
  aci/resource_aci_spanspanlbl.go
  aci/resource_aci_spansrcgrp.go
  aci/resource_aci_vmmdomp.go
  aci/resource_aci_vzany.go
  aci/resource_aci_vzbrcp.go
  aci/resource_aci_vzcpif.go
  aci/resource_aci_vzentry.go
  aci/resource_aci_vzfilter.go
  aci/resource_aci_vzsubj.go
  aci/resource_aci_vztaboo.go
  aci/utils.go
Labels: size/XL

#48 CACIT-34: added logic for filter manage in contract resource
  aci/resource_aci_vzbrcp.go
  website/docs/r/vzbrcp.html.markdown
Labels: documentation, size/L

#51 Epg to contract
  aci/data_source_aci_fvrsprovcons.go
  aci/provider.go
  aci/resource_aci_fvrsprovcons.go
  aci/resource_aci_fvrsprovcons_test.go
  examples/epg_to_contract/main.tf
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/client.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/fabricNodeBlk_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/firmwareCtrlrFwP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/firmwareDownload_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/firmwareFirmware_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/firmwareOSource_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/fvRsCons_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/fvRsProv_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/maintCtrlrMaintP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/maintMaintGrp_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/maintMaintP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/maintUpgJob_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/service_manager.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/syntheticMaintPSwitchDetails_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/syntheticMaintPValidate_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/topSystem_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/trigSchedP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/fabric_node_blk.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/firmware_ctrlrfwp.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/firmware_download.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/firmware_firmware.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/firmware_o_source.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/fv_rs_cons.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/fv_rs_prov.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/maint_ctrlr_maint_p.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/maint_maint_grp.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/maint_maint_p.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/maint_upg_job.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/synthetic_maint_p_switch_details.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/synthetic_maint_p_validate.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/synthetic_switch_maint_p_validate.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/top_system.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/trig_sched_p.go
  vendor/modules.txt
  website/aci.erb
  website/docs/d/epgtocontract.html.markdown
  website/docs/r/epgtocontract.html.markdown
Labels: dependencies, size/XXL

#52 Cacit 35 filter entry inline with contract
  aci/resource_aci_vzbrcp.go
  website/docs/r/vzbrcp.html.markdown
Labels: documentation, size/XL

#54 fixed crash issue while update
  aci/data_source_aci_fvrsprovcons.go
  aci/resource_aci_fvrsprovcons.go
  aci/resource_aci_vzbrcp.go
  aci/resource_aci_vzentry.go
  examples/entry/entry.tf
  examples/epg_to_contract/main.tf
  examples/inline_entry/entry_main.tf
Labels: size/L

#55 Cacit 36 accepted value for relation object
  aci/resource_aci_cloudctxprofile.go
  aci/resource_aci_cloudepg.go
  aci/resource_aci_cloudextepg.go
  aci/resource_aci_cloudsubnet.go
  aci/resource_aci_configexportp.go
  aci/resource_aci_configimportp.go
  aci/resource_aci_fcdomp.go
  aci/resource_aci_firmwarefwgrp.go
  aci/resource_aci_fvaepg.go
  aci/resource_aci_fvap.go
  aci/resource_aci_fvbd.go
  aci/resource_aci_fvctx.go
  aci/resource_aci_fvsubnet.go
  aci/resource_aci_fvtenant.go
  aci/resource_aci_infraaccbndlgrp.go
  aci/resource_aci_infraaccportgrp.go
  aci/resource_aci_infrahports.go
  aci/resource_aci_infraleafs.go
  aci/resource_aci_infraportblk.go
  aci/resource_aci_l3extdomp.go
  aci/resource_aci_l3extinstp.go
  aci/resource_aci_l3extlifp.go
  aci/resource_aci_l3extout.go
  aci/resource_aci_l3extsubnet.go
  aci/resource_aci_maintmaintgrp.go
  aci/resource_aci_maintmaintp.go
  aci/resource_aci_physdomp.go
  aci/resource_aci_spansrcgrp.go
  aci/resource_aci_vmmdomp.go
  aci/resource_aci_vzany.go
  aci/resource_aci_vzbrcp.go
  aci/resource_aci_vzcpif.go
  aci/resource_aci_vzfilter.go
  aci/resource_aci_vzsubj.go
Labels: size/XXL

#56 fixed idempotency issue
  aci/resource_aci_vzentry.go
  examples/entry/entry.tf
Labels: size/XS

#58 CACIT-46 Added infraNodeBlk resource
  aci/data_source_aci_infranodeblk.go
  aci/provider.go
  aci/resource_aci_infranodeblk.go
  aci/resource_aci_infranodeblk_test.go
  examples/aci_node_block/main.tf
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/client.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/infraAccBndlGrp_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/infraNodeBlk_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/infra_node_blk.go
  vendor/modules.txt
  website/aci.erb
  website/docs/d/infranodeblk.html.markdown
  website/docs/r/infranodeblk.html.markdown
Labels: dependencies, documentation, size/XL

#59 resolve issue with physdom
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/physDomP_service.go
  vendor/modules.txt
Labels: dependencies, size/XS

#60 fixed the dn to name convertion
  aci/resource_aci_infraaccbndlgrp.go
Labels: size/XS

#61 Added support for json and yaml payload to rest resource
  aci/resource_rest.go
  examples/rest/main.tf
  examples/rest/rest.tf
  go.mod
  go.sum
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/parserc.go
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/gopkg.in/yaml.v2/yamlprivateh.go
  vendor/modules.txt
  website/docs/r/rest.html.markdown
Labels: dependencies, size/XXL

#62 CACIT-47 added resource fvrsdomatt
  aci/data_source_aci_fvrsdomatt.go
  aci/provider.go
  aci/resource_aci_fvrsdomatt.go
  aci/resource_aci_fvrsdomatt_test.go
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/fvRsDomAtt_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/vmmSecP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/fv_rs_dom_att.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/vmm_sec_p.go
  vendor/modules.txt
  website/aci.erb
  website/docs/d/fvrsdomatt.html.markdown
  website/docs/r/fvrsdomatt.html.markdown
Labels: dependencies, documentation, size/XXL

#63 Physdom fix
  CHANGELOG.md
  aci/resource_aci_fcdomp.go
  aci/resource_aci_l3extdomp.go
  aci/resource_aci_physdomp.go
  aci/resource_aci_vmmdomp.go
  examples/physdom/main.tf
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/fcDomP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/l3extDomP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/vmmDomP_service.go
  vendor/modules.txt
Labels: dependencies, size/M

#69 website/docs: Replace repeated 'node_block'
  website/aci.erb
  website/docs/d/fabricnodeblk.html.markdown
  website/docs/r/fabricnodeblk.html.markdown
Labels: documentation, size/XS

#71 Updated relations payload
  aci/resource_aci_cloudctxprofile.go
  aci/resource_aci_configexportp.go
  aci/resource_aci_configimportp.go
  aci/resource_aci_fcdomp.go
  aci/resource_aci_infraaccbndlgrp.go
  aci/resource_aci_infraaccportgrp.go
  aci/resource_aci_infrahports.go
  aci/resource_aci_infraleafs.go
  aci/resource_aci_l3extdomp.go
  aci/resource_aci_l3extinstp.go
  aci/resource_aci_l3extsubnet.go
  aci/resource_aci_maintmaintp.go
  aci/resource_aci_physdomp.go
  aci/resource_aci_spansrcgrp.go
  aci/resource_aci_vmmdomp.go
  aci/resource_aci_vzfilter.go
  aci/resource_aci_vzsubj.go
  go.mod
  go.sum
  vendor/github.com/ciscoecosystem/aci-go-client/client/cloudCtxProfile_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/configExportP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/configImportP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/fabricNode_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/fcDomP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/infraAccBndlGrp_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/infraAccPortGrp_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/infraHPortS_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/infraLeafS_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/l3extDomP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/l3extInstP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/l3extSubnet_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/maintMaintP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/physDomP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/spanSrcGrp_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/vmmDomP_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/vzFilter_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/client/vzSubj_service.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/fabric_node.go
  vendor/github.com/ciscoecosystem/aci-go-client/models/firmware_o_source.go
  vendor/modules.txt
Labels: dependencies, size/XL
